version: "3.8"
services:
  noteapp-dynamodb-local:
    image: amazon/dynamodb-local:latest
    container_name: noteapp-dynamodb-local
    ports:
      - "8000:8000"
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ."
    volumes:
      - "./dynamodb_data:/home/dynamodblocal/data"
    working_dir: /home/dynamodblocal
  noteapp-dynamodb-admin:
    image: aaronshaf/dynamodb-admin
    ports:
      - "8001:8001"
    environment:
      DYNAMO_ENDPOINT: "http://noteapp-dynamodb-local:8000"
      AWS_REGION: "local"
      AWS_ACCESS_KEY_ID: "local"
      AWS_SECRET_ACCESS_KEY: "local"
    depends_on:
      - noteapp-dynamodb-local
